apiVersion: v1
kind: Secret
metadata:
  name: lgtm-object-storage
  namespace: observability
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: REPLACE_ME_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: REPLACE_ME_SECRET_KEY
  S3_ENDPOINT: s3.REPLACE_ME_REGION.amazonaws.com
  S3_REGION: REPLACE_ME_REGION
  MIMIR_BLOCKS_BUCKET: REPLACE_ME_MIMIR_BLOCKS_BUCKET
  MIMIR_RULER_BUCKET: REPLACE_ME_MIMIR_RULER_BUCKET
  MIMIR_ALERTMANAGER_BUCKET: REPLACE_ME_MIMIR_ALERTMANAGER_BUCKET
  LOKI_CHUNKS_BUCKET: REPLACE_ME_LOKI_CHUNKS_BUCKET
  LOKI_RULER_BUCKET: REPLACE_ME_LOKI_RULER_BUCKET
  TEMPO_TRACES_BUCKET: REPLACE_ME_TEMPO_TRACES_BUCKET
