apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: lgtm-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-agents
  labels:
    app.kubernetes.io/part-of: lgtm-platform
    environment: production
