apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-extra-datasources
  namespace: obs-lgtm
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.obs-lgtm.svc.cluster.local
        isDefault: false
        jsonData:
          maxLines: 1000

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.obs-lgtm.svc.cluster.local:3200
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - key: service.name
                value: service
              - key: k8s.namespace.name
                value: namespace
            filterByTraceID: true
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
