global:
  extraEnvFrom:
    - secretRef:
        name: lgtm-object-storage

tempo:
  reportingEnabled: false

server:
  logLevel: info

storage:
  trace:
    backend: s3
    s3:
      bucket: ${TEMPO_TRACES_BUCKET}
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      access_key: ${AWS_ACCESS_KEY_ID}
      secret_key: ${AWS_SECRET_ACCESS_KEY}
      insecure: false

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  jaeger:
    grpc:
      enabled: false
    thriftHttp:
      enabled: false
    thriftBinary:
      enabled: false
    thriftCompact:
      enabled: false
  zipkin:
    enabled: false

distributor:
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "4"
      memory: 4Gi

ingester:
  replicas: 3
  persistence:
    enabled: true
    size: 100Gi
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 12Gi

querier:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

queryFrontend:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

compactor:
  replicas: 1
  config:
    compaction:
      block_retention: 336h
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

metricsGenerator:
  enabled: true
  replicas: 2
  config:
    storage:
      remote_write:
        - url: http://mimir-nginx.observability.svc.cluster.local/api/v1/push
          headers:
            X-Scope-OrgID: production
    processor:
      service_graphs:
        dimensions:
          - service.namespace
          - deployment.environment
      span_metrics:
        dimensions:
          - service.namespace
          - deployment.environment

gateway:
  enabled: true
  replicas: 2

memcached:
  enabled: true
