apiVersion: v1
kind: Secret
metadata:
  name: lgtm-object-storage
  namespace: observability
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: learning-lab-access-key
  AWS_SECRET_ACCESS_KEY: learning-lab-secret-key-change-me
  S3_ENDPOINT: lgtm-minio.observability.svc.cluster.local:9000
  S3_REGION: local-1
  MIMIR_BLOCKS_BUCKET: learning-lab-mimir-blocks
  MIMIR_RULER_BUCKET: learning-lab-mimir-ruler
  MIMIR_ALERTMANAGER_BUCKET: learning-lab-mimir-alertmanager
  LOKI_CHUNKS_BUCKET: learning-lab-loki-chunks
  LOKI_RULER_BUCKET: learning-lab-loki-ruler
  TEMPO_TRACES_BUCKET: learning-lab-tempo-traces
