apiVersion: v1
kind: Namespace
metadata:
  name: obs-lgtm
  labels:
    env: poc
    system: observability-poc
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs-signoz
  labels:
    env: poc
    system: observability-poc
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: obs-router
  labels:
    env: poc
    system: observability-poc
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-apps
  labels:
    env: poc
    system: observability-poc
    team: devops
